repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.3
    hooks:
      - id: reorder-python-imports
        files: ^api/src/.*\.py$

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: ^api/src/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        files: ^api/src/.*\.py$

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
        files: ^api/src/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        files: ^api/src/.*\.py$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        files: ^api/src/.*\.py$
        args: [--py38-plus]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^frontend/src/.*\.(ts|tsx|js|css|html|json)$
        args:
          ["--config=frontend/.prettierrc.cjs", "--ignore-path=frontend/.prettierignore"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.34.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - eslint-config-react-app
          - typescript
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - eslint-config-prettier # turns off all rules that might conflict with prettier
          - eslint-plugin-jsx-a11y # checks accessibility rules on jsx elements
          - eslint-plugin-prettier # runs prettier as an eslint rule
          - eslint-plugin-react # react specific linting rules
          - eslint-plugin-react-hooks # enforces the rules of hooks
        files: ^frontend/src/.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: ["--config=frontend/.eslintrc.json", "--ignore-path=frontend/.eslintignore", "--fix"]
