name: Test backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install -r backend/dev-requirements.txt
      - name: Setup secrets
        run: |
          cp backend/.env.example backend/.env
      - name: Test with pytest
        run: |
          cd backend && python3 -m pytest
